import { englishCoreUiCopy } from "@/lib/ui/copy/core";

export const englishUiCopy = {
  ...englishCoreUiCopy,
  dashboard: {
    workspace: "Workspace",
    title: "Dashboard",
    refreshPrices: "Refresh prices",
    refreshing: "Refreshing...",
    portfolioSummary: "Portfolio summary",
    portfolioValue: "Portfolio value",
    costBasis: "Cost basis",
    unrealizedPnl: "Unrealized P&L",
    realizedPnl: "Realized P&L",
    fees: "Fees",
    vsCostBasis: "vs cost basis",
    closedTrades: "Closed trades",
    allTransactions: "All transactions",
    openPositionsOnly: "Open positions only",
    prices: "Prices",
    coverage: "Coverage",
    priced: "Priced",
    missing: "Missing",
    closed: "Closed",
    latestCache: "Latest cache",
    updateMarketData: "Update market data",
    holdings: "Holdings",
    openPositions: "Open positions",
    viewAll: "View all",
    noPriceCache: "No price cache",
    stale: (age: string) => `Stale ${age}`,
    age: {
      noCachedData: "No cached data",
      justUpdated: "Just updated",
      minutesAgo: (minutes: number) => `${minutes} min ago`,
      hoursAgo: (hours: number) => `${hours}h ago`,
    },
    refresh: {
      quotesUpdated: (count: string) => `${count} quotes updated`,
      providerTimestamp: (timestamp: string) => `Provider timestamp ${timestamp}`,
      symbolsNeedReview: (count: string) => `${count} symbols still need review`,
      successTitle: "Market data updated",
      warningTitle: "Market data updated with warnings",
      startedTitle: "Market data refresh started",
      statusLoading: "Checking refresh status...",
      statusUnavailable: "Refresh status is unavailable.",
      runningProgress: (processed: number, total: number, symbol: string | null) =>
        total > 0
          ? `Refreshing ${processed}/${total}${symbol == null ? "" : ` | ${symbol}`}`
          : "Preparing refresh...",
      errorTitle: "Market data refresh failed",
      fallbackErrorBody: "The dashboard is still using the latest cached prices.",
    },
  },
  charts: {
    common: {
      timeframes: {
        "1D": "1D",
        "5D": "5D",
        "1W": "1W",
        "1M": "1M",
        "3M": "3M",
        YTD: "YTD",
        "1Y": "1Y",
        START: "Start",
        ALL: "All",
      },
      dragToCompare: "Drag across the chart to compare",
      to: "to",
      noChartData: "No chart data",
      fromRangeStart: "from range start",
      latest: "Latest",
      high: "High",
      low: "Low",
      range: "Range",
    },
    benchmark: {
      eyebrow: "Performance",
      titleDefault: "Performance vs benchmark",
      titleWithSymbol: (symbol: string) => `Performance vs ${symbol}`,
      performanceMode: "Benchmark performance mode",
      timeframe: "Benchmark chart timeframe",
      rangeSummary: "Benchmark comparison range summary",
      portfolio: "Portfolio",
      benchmark: "Benchmark",
      latestGap: "Latest gap",
      gap: "Gap",
      comparisonPicker: {
        add: "+ Add comparison",
        adding: "Adding...",
        clear: "Clear all",
        close: "Close",
        dialogTitle: "Add stock or ETF comparison",
        aria: "Benchmark comparison overlays",
        noMatches: "No matching stocks or ETFs",
        remove: (symbol: string) => `Remove ${symbol} comparison`,
        saved: "Added",
        search: "Search",
        searchError: "Comparison could not be added right now.",
        searchPlaceholder: "Type SPY, QQQ, TDEX, or a company name",
        searching: "Searching...",
      },
      modes: {
        INDEXED: "Return",
        GAP: "Gap",
        DRAWDOWN: "Drawdown",
      },
      returnBasis: {
        label: "Chart return basis",
        options: {
          TWR: "TWR",
          MWR: "MWR",
          ABSOLUTE: "Absolute",
        },
        TWR: {
          summaryLabel: "TWR return",
          summaryValue: "TWR",
          portfolioName: "Portfolio TWR",
          yAxisLabel: "TWR",
          hint: "The chart uses cash-flow-adjusted time-weighted return, indexed from 100.",
        },
        MWR: {
          summaryLabel: "MWR return",
          summaryValue: "MWR",
          portfolioName: "Portfolio MWR",
          yAxisLabel: "MWR",
          hint: "The chart shows annualized money-weighted return from dated cash flows and ending market value.",
        },
        ABSOLUTE: {
          summaryLabel: "Absolute return",
          summaryValue: "Absolute",
          portfolioName: "Portfolio absolute return",
          yAxisLabel: "Absolute",
          hint: "The chart shows market value return against cumulative net invested capital.",
        },
      },
      modeCopy: {
        INDEXED: {
          portfolioName: "Portfolio TWR",
          benchmarkName: "Benchmark return",
          yAxisLabel: "TWR",
        },
        GAP: {
          portfolioName: "Portfolio gap",
          benchmarkName: "Benchmark baseline",
          yAxisLabel: "Gap",
        },
        DRAWDOWN: {
          portfolioName: "Portfolio drawdown",
          benchmarkName: "Benchmark drawdown",
          yAxisLabel: "Drawdown",
        },
      },
      basis: {
        sameCurrencyFallback: "Same-currency return",
        sameCurrency: (currency: string) => `${currency} return`,
        nativeCurrencyFallback: "Native-currency benchmark return",
        nativeCurrency: (currency: string) => `${currency} benchmark return, compared by %`,
        performanceReturn: "Performance return",
      },
      absoluteSummary: {
        label: "Absolute performance summary",
        absoluteReturn: "Absolute return",
        totalPnl: "Total P&L",
        netInvested: "Net invested",
        timeWeighted: "Chart return",
        timeWeightedValue: "TWR",
        note: "Note",
        hints: {
          absoluteReturn:
            "Money-result return from total P&L divided by positive net invested capital.",
          totalPnl:
            "Realized P&L plus unrealized P&L, with fees included in the existing position math.",
          netInvested: "Buy cash outflow minus sell proceeds.",
          timeWeighted: "The chart uses cash-flow-adjusted time-weighted return, indexed from 100.",
          note: "Why absolute return may be unavailable.",
        },
        unavailable: {
          noTransactions: "Add transactions to calculate absolute return.",
          mixedCurrency: "Absolute return is paused for mixed transaction currencies.",
          missingMarketValue: "Absolute return needs current market value for open holdings.",
          noPositiveNetInvested: "Absolute return needs positive net invested capital.",
        },
      },
      unavailable: {
        noTransactions: "Add a transaction to start the benchmark chart.",
        mixedCurrency: "Benchmark comparison is disabled for mixed transaction currencies.",
        missingPortfolioHistory: "Price history is incomplete for full-portfolio performance.",
        currencyMismatchFallback: "The benchmark currency does not match the portfolio currency.",
        currencyMismatch: (symbol: string, currency: string) =>
          `${symbol} is not quoted in ${currency}.`,
        missingBenchmarkFallback: "Set a benchmark to enable comparison.",
        missingBenchmarkHistory: (symbol: string) => `No cached history for ${symbol}.`,
        missingAbsoluteReturn:
          "Absolute return chart needs positive net invested capital and comparable benchmark history.",
        default: "Benchmark chart is not available yet.",
      },
    },
    portfolio: {
      eyebrow: "Portfolio value",
      title: "Portfolio value history",
      timeframe: "Portfolio chart timeframe",
      rangeSummary: "Portfolio value range summary",
      unavailable: {
        noTransactions: "Add a transaction to start the portfolio chart.",
        mixedCurrency: "Portfolio chart is paused for mixed transaction currencies.",
        missingPortfolioHistory: "Price history is incomplete for full-portfolio performance.",
        default: "No portfolio chart data yet.",
      },
    },
  },
  holdings: {
    pageEyebrow: "Holdings",
    pageTitle: "Positions",
    statusLabel: "Holdings status",
    open: "Open",
    priced: "Priced",
    missing: "Missing",
    latestCache: "Latest cache",
    table: {
      eyebrow: "Holdings",
      title: "Current positions",
      toolsLabel: "Holdings table tools",
      filtersLabel: "Holdings filters",
      performanceBasisLabel: "Performance comparison basis",
      performanceBasis: {
        price: "Price history",
        cost: "Cost basis",
      },
      performanceTimeframesLabel: "Performance timeframe",
      refreshPrices: "Refresh prices",
      refreshing: "Refreshing...",
      refreshStarted: "Market data refresh started.",
      noOpenPositions:
        "No open positions yet. Add a buy transaction and holdings will appear here.",
      searchPlaceholder: "Symbol, name, market",
      positionsUnit: "positions",
      noMatches: "No positions match the current filters.",
      shownTotal: "Shown total",
      noPriceYet: "No price yet",
      noData: "No data",
      asOf: (date: string) => `as of ${date}`,
      updatedWithIssues: (count: number) =>
        `Updated prices with ${count} symbols still needing review.`,
      updatedPrices: (count: number) => `Updated ${count} prices.`,
      refreshFailed: "Market data refresh failed.",
      filter: {
        all: "All",
        gain: "Gain",
        loss: "Loss",
        missing: "Missing price",
      },
      timeframes: {
        "1D": "1D",
        "1W": "1W",
        "1M": "1M",
        YTD: "YTD",
        "1Y": "1Y",
        "3Y": "3Y",
        "5Y": "5Y",
        MAX: "MAX",
      },
      columns: {
        symbol: "Symbol",
        quantity: "Quantity",
        averageCost: "Average cost",
        totalCost: "Total cost",
        lastPrice: "Last price",
        oneDayGain: "1D",
        performance: (timeframe: string) => `Performance ${timeframe}`,
        marketValue: "Market value",
        unrealizedPnl: "Unrealized P&L",
        weight: "Weight",
      },
      lots: {
        expandColumn: "Purchase lots",
        expand: (symbol: string) => `Show ${symbol} purchase lots`,
        collapse: (symbol: string) => `Hide ${symbol} purchase lots`,
        noOpenLots: "No open purchase lots.",
        openLot: "Open lot",
        fee: (value: string) => `Fee ${value}`,
        originalQuantity: (quantity: string) => `Original ${quantity}`,
        costLabel: "Cost",
        columns: {
          date: "Buy date",
          price: "Buy price",
          quantity: "Remaining quantity",
          gain: "Total gain",
          value: "Value",
          note: "Note",
        },
      },
    },
    summary: {
      openPositions: "Open positions",
      openCostBasis: "Open cost basis",
      marketValue: "Market value",
      unrealizedPnl: "Unrealized P&L",
      realizedPnl: "Realized P&L",
      noOpenHoldings: "No open holdings yet",
      openLedger: (count: number) => `${count} positions are still open from the trade ledger`,
      calculatedOpenOnly: "Calculated from open positions only",
      usingCachedPrices: "Using cached prices",
      usingCachedPricesAsOf: (date: string) => `Using cached prices as of ${date}`,
      openGainLoss: "Open-position gain or loss versus cost",
      closedTradeResult: "Closed-trade result through now",
      waiting: "Waiting",
      waitingForPrice: "waiting for price",
      mixedCurrency: "Mixed currency",
      currencyBreakdown: (currency: string, value: string) => `${currency}: ${value}`,
      priceCoverageNoOpen: "No open positions yet",
      priceCoverageFull: (count: number) => `Cached prices cover all ${count} positions`,
      priceCoverageFullAsOf: (count: number, date: string) =>
        `Cached prices cover all ${count} positions as of ${date}`,
      priceCoveragePartial: (priced: number, open: number, waiting: string) =>
        `${priced} of ${open} positions priced; waiting for ${waiting}`,
      moreSymbols: (count: number) => ` +${count} more`,
    },
    allocation: {
      ariaLabel: "Holdings allocation chart",
      other: "Other",
      positions: (count: number) => `${count} positions`,
      ofHoldings: "of holdings",
    },
  },
  transactions: {
    pageEyebrow: "Ledger",
    pageTitle: "Transactions",
    pageDescription: "Record buys, sells, and fees without preselecting an instrument.",
    aggregateReadOnly:
      "All portfolios is read-only. Choose a specific portfolio before adding, editing, deleting, importing, exporting, or refreshing market data.",
    summaryLabel: "Transaction summary",
    recorded: "Recorded",
    traded: "Traded",
    open: "Open",
    latest: "Latest",
    selectable: "Selectable",
    allInstruments: "All instruments",
    syncing: "Updating transactions...",
    excel: {
      eyebrow: "Excel",
      title: "Import / export transactions",
      downloadTemplate: "Download template",
      exportLedger: "Export ledger",
      downloadingTemplate: "Downloading template...",
      exportingLedger: "Exporting ledger...",
      file: "Excel file",
      selectedFile: "Selected file",
      chooseFile: "Choose file",
      noFileSelected: "No file selected",
      preview: "Preview",
      previewing: "Previewing...",
      importReady: "Import ready rows",
      importing: "Importing...",
      previewSummary: "Excel import summary",
      total: "Total",
      ready: "Ready",
      skipped: "Skipped",
      error: "Errors",
      row: (rowNumber: number) => `Row ${rowNumber}`,
      chooseFileFirst: "Choose an .xlsx file first.",
      importFailed: "Excel import failed.",
      imported: (count: number) => `${count} transactions imported.`,
    },
    form: {
      editEyebrow: "Edit transaction",
      newEyebrow: "New transaction",
      updateTitle: "Update trade",
      recordTitle: "Record trade",
      instrument: "Instrument",
      instrumentHint: "Search a saved instrument or add a new one.",
      close: "Close",
      clearInstrumentSearch: "Clear instrument search",
      addInstrument: "Add instrument",
      addingInstrument: "Adding instrument...",
      searchInstrument: "Search instrument",
      searchInstrumentPlaceholder: "Type ASTS03, AAPL, or a company name",
      searching: "Searching...",
      noMatchingInstruments: "No matching instruments",
      noInstruments: "No instruments are available. Add an instrument before recording trades.",
      chooseInstrument: "Choose an instrument",
      currentQuantity: (quantity: string) => `Current quantity: ${quantity} units`,
      selectBeforeSaving: "Select a matching instrument before saving.",
      tradeDate: "Trade date",
      side: "Side",
      broker: "Broker",
      buy: "Buy",
      sell: "Sell",
      quantity: "Quantity",
      price: "Price",
      fee: "Fee",
      notes: "Notes",
      notesPlaceholder: "Optional note, such as fill context or trade reason",
      cancelEdit: "Cancel edit",
      updating: "Updating...",
      saving: "Saving...",
      refreshing: "Refreshing...",
      updateTransaction: "Update transaction",
      saveTransaction: "Save transaction",
      couldNotSave: "Transaction could not be saved.",
      couldNotUpdate: "Transaction could not be updated.",
      transactionUpdated: "Transaction updated.",
      transactionSaved: "Transaction saved.",
      instrumentSearchUnavailable: "Instrument search is unavailable right now.",
      instrumentCouldNotSave: "Instrument could not be saved.",
      instrumentAlreadyAdded: (symbol: string) =>
        `${symbol} is already saved. Select it from the Instrument field below.`,
      addedAndSelected: (symbol: string) => `${symbol} added and selected.`,
      selected: (symbol: string) => `${symbol} selected.`,
      insufficientQuantity: (quantity: string) =>
        `Sell quantity is greater than current holdings. Maximum sellable quantity is ${quantity}.`,
      saved: "Saved",
      add: "Add",
    },
    table: {
      eyebrow: "Ledger",
      title: "Latest transactions",
      toolsLabel: "Transaction table tools",
      noTransactions: "No transactions yet. The first recorded trade will appear here immediately.",
      searchPlaceholder: "Symbol, date, note",
      transactionsUnit: "transactions",
      noMatches: "No transactions match the current search.",
      deleteCouldNot: "Transaction could not be deleted.",
      deleteConfirm: (side: string, quantity: string, symbol: string, date: string) =>
        `Delete ${side} ${quantity} ${symbol} from ${date}?`,
      refreshing: "Updating transactions...",
      deleting: "Deleting...",
      delete: "Delete",
      edit: "Edit",
      columns: {
        date: "Date",
        instrument: "Instrument",
        side: "Side",
        broker: "Broker",
        portfolio: "Portfolio",
        quantity: "Quantity",
        price: "Price",
        fee: "Fee",
        net: "Net",
        notes: "Notes",
        actions: "Actions",
      },
    },
  },
} as const;
