import { thaiCoreUiCopy } from "@/lib/ui/copy/core";

export const thaiUiCopy = {
  ...thaiCoreUiCopy,
  dashboard: {
    workspace: "พื้นที่ทำงาน",
    title: "ภาพรวม",
    refreshPrices: "รีเฟรชราคา",
    refreshing: "กำลังรีเฟรช...",
    portfolioSummary: "สรุปพอร์ต",
    portfolioValue: "มูลค่าพอร์ต",
    costBasis: "ต้นทุน",
    unrealizedPnl: "P&L ที่ยังไม่เกิดขึ้นจริง",
    realizedPnl: "P&L ที่เกิดขึ้นจริง",
    fees: "ค่าธรรมเนียม",
    vsCostBasis: "เทียบกับต้นทุน",
    closedTrades: "เทรดปิดแล้ว",
    allTransactions: "ทุกรายการ",
    openPositionsOnly: "เฉพาะสถานะที่เปิดอยู่",
    prices: "ราคา",
    coverage: "ความครอบคลุม",
    priced: "มีราคา",
    missing: "ขาดราคา",
    closed: "ปิดแล้ว",
    latestCache: "แคชล่าสุด",
    updateMarketData: "อัปเดตข้อมูลตลาด",
    holdings: "หุ้นที่ถือ",
    openPositions: "สถานะที่เปิดอยู่",
    viewAll: "ดูทั้งหมด",
    noPriceCache: "ไม่มีแคชราคา",
    stale: (age: string) => `เก่า ${age}`,
    age: {
      noCachedData: "ไม่มีข้อมูลแคช",
      justUpdated: "เพิ่งอัปเดต",
      minutesAgo: (minutes: number) => `${minutes} นาทีที่แล้ว`,
      hoursAgo: (hours: number) => `${hours} ชม.ที่แล้ว`,
    },
    refresh: {
      quotesUpdated: (count: string) => `อัปเดต ${count} ราคา`,
      providerTimestamp: (timestamp: string) => `เวลา provider ${timestamp}`,
      symbolsNeedReview: (count: string) => `${count} symbols ยังต้องตรวจสอบ`,
      successTitle: "อัปเดตข้อมูลตลาดแล้ว",
      warningTitle: "อัปเดตข้อมูลตลาดแล้ว แต่มีคำเตือน",
      startedTitle: "เริ่มรีเฟรชข้อมูลตลาดแล้ว",
      statusLoading: "กำลังตรวจสอบสถานะรีเฟรช...",
      statusUnavailable: "ไม่สามารถอ่านสถานะรีเฟรชได้",
      runningProgress: (processed: number, total: number, symbol: string | null) =>
        total > 0
          ? `กำลังรีเฟรช ${processed}/${total}${symbol == null ? "" : ` | ${symbol}`}`
          : "กำลังเตรียมรีเฟรช...",
      errorTitle: "รีเฟรชข้อมูลตลาดไม่สำเร็จ",
      fallbackErrorBody: "แดชบอร์ดยังใช้ราคาจากแคชล่าสุด",
    },
  },
  charts: {
    common: {
      timeframes: {
        "1D": "1D",
        "5D": "5D",
        "1W": "1W",
        "1M": "1M",
        "3M": "3M",
        YTD: "YTD",
        "1Y": "1Y",
        "3Y": "3Y",
        "5Y": "5Y",
        START: "เริ่มต้น",
        ALL: "ทั้งหมด",
      },
      dragToCompare: "ลากบนกราฟเพื่อเปรียบเทียบ",
      to: "ถึง",
      noChartData: "ไม่มีข้อมูลกราฟ",
      fromRangeStart: "จากจุดเริ่มช่วง",
      latest: "ล่าสุด",
      high: "สูงสุด",
      low: "ต่ำสุด",
      range: "ช่วง",
    },
    benchmark: {
      eyebrow: "ผลตอบแทน",
      titleDefault: "ผลตอบแทนเทียบ benchmark",
      titleWithSymbol: (symbol: string) => `ผลตอบแทนเทียบ ${symbol}`,
      performanceMode: "โหมดผลตอบแทน benchmark",
      timeframe: "ช่วงเวลาของกราฟ benchmark",
      rangeSummary: "สรุปช่วงเปรียบเทียบ benchmark",
      portfolio: "พอร์ต",
      benchmark: "Benchmark",
      latestGap: "Gap ล่าสุด",
      gap: "Gap",
      annualized: {
        label: "ผลตอบแทนเฉลี่ยต่อปี (TWR)",
        portfolio: "ผลตอบแทนเฉลี่ยต่อปี",
        perYear: (value: string) => `${value}/ปี`,
        hint: "ผลตอบแทนเฉลี่ยต่อปีแบบ time-weighted (TWR) ตั้งแต่เริ่มลงทุน — ตัดผลของจังหวะเติม/ถอนเงินทั้งสองฝั่ง จึงเทียบกับ benchmark ได้อย่างเป็นธรรม",
        vs: (symbol: string) => `เทียบ ${symbol}`,
        gapHint: "ส่วนต่างผลตอบแทนเฉลี่ยต่อปีของพอร์ตหักด้วย benchmark (บวก = ชนะดัชนี)",
      },
      comparisonPicker: {
        add: "+ Add comparison",
        adding: "กำลังเพิ่ม...",
        clear: "Clear all",
        close: "ปิด",
        dialogTitle: "เพิ่มหุ้นหรือ ETF เพื่อเทียบ",
        aria: "Benchmark comparison overlays",
        noMatches: "ไม่พบหุ้นหรือ ETF ที่ตรงกัน",
        remove: (symbol: string) => `Remove ${symbol} comparison`,
        saved: "เพิ่มแล้ว",
        search: "ค้นหา",
        searchError: "ไม่สามารถเพิ่ม comparison ได้ตอนนี้",
        searchPlaceholder: "พิมพ์ SPY, QQQ, TDEX หรือชื่อบริษัท",
        searching: "กำลังค้นหา...",
      },
      modes: {
        INDEXED: "Return",
        GAP: "Gap",
        DRAWDOWN: "Drawdown",
      },
      returnBasis: {
        label: "Chart return basis",
        options: {
          TWR: "TWR",
          MWR: "MWR",
          ABSOLUTE: "Absolute",
        },
        TWR: {
          summaryLabel: "TWR return",
          summaryValue: "TWR",
          portfolioName: "Portfolio TWR",
          yAxisLabel: "TWR",
          hint: "The chart uses cash-flow-adjusted time-weighted return, indexed from 100.",
        },
        MWR: {
          summaryLabel: "MWR return",
          summaryValue: "MWR",
          portfolioName: "Portfolio MWR",
          yAxisLabel: "MWR",
          hint: "The chart shows annualized money-weighted return from dated cash flows and ending market value.",
        },
        ABSOLUTE: {
          summaryLabel: "Absolute return",
          summaryValue: "Absolute",
          portfolioName: "Portfolio absolute return",
          yAxisLabel: "Absolute",
          hint: "The chart shows market value return against cumulative net invested capital.",
        },
      },
      modeCopy: {
        INDEXED: {
          portfolioName: "Portfolio TWR",
          benchmarkName: "Benchmark return",
          yAxisLabel: "TWR",
        },
        GAP: {
          portfolioName: "Portfolio gap",
          benchmarkName: "Benchmark baseline",
          yAxisLabel: "Gap",
        },
        DRAWDOWN: {
          portfolioName: "Portfolio drawdown",
          benchmarkName: "Benchmark drawdown",
          yAxisLabel: "Drawdown",
        },
      },
      basis: {
        sameCurrencyFallback: "ผลตอบแทนสกุลเงินเดียวกัน",
        sameCurrency: (currency: string) => `ผลตอบแทน ${currency}`,
        nativeCurrencyFallback: "ผลตอบแทน benchmark ตามสกุลเงินต้นทาง",
        nativeCurrency: (currency: string) => `ผลตอบแทน benchmark ${currency}, เทียบเป็น %`,
        performanceReturn: "ผลตอบแทน",
      },
      absoluteSummary: {
        label: "สรุปผลตอบแทนแบบ absolute",
        absoluteReturn: "Absolute return",
        totalPnl: "Total P&L",
        netInvested: "Net invested",
        timeWeighted: "ผลตอบแทนกราฟ",
        timeWeightedValue: "TWR",
        note: "หมายเหตุ",
        hints: {
          absoluteReturn:
            "ผลตอบแทนจากมุมเงินจริง คำนวณจาก Total P&L หารด้วย net invested ที่เป็นบวก",
          totalPnl: "Realized P&L รวมกับ unrealized P&L โดยใช้ fee จาก logic สถานะเดิม",
          netInvested: "เงินซื้อสุทธิ หัก proceeds จากการขาย",
          timeWeighted: "กราฟใช้ time-weighted return ที่ปรับ cash flow แล้ว และตั้งต้นที่ 100",
          note: "เหตุผลที่ absolute return อาจยังแสดงไม่ได้",
        },
        unavailable: {
          noTransactions: "เพิ่มรายการซื้อขายเพื่อคำนวณ absolute return",
          mixedCurrency: "หยุดคำนวณ absolute return เมื่อรายการซื้อขายมีหลายสกุลเงิน",
          missingMarketValue: "absolute return ต้องใช้มูลค่าตลาดล่าสุดของ holdings ที่ยังเปิดอยู่",
          noPositiveNetInvested: "absolute return ต้องมี net invested เป็นบวก",
        },
      },
      unavailable: {
        noTransactions: "เพิ่มรายการซื้อขายเพื่อเริ่มกราฟ benchmark",
        mixedCurrency: "ปิดการเปรียบเทียบ benchmark เมื่อประวัติรายการซื้อขายมีหลายสกุลเงิน",
        missingPortfolioHistory: "ประวัติราคาไม่ครบสำหรับ performance ของทั้งพอร์ต",
        currencyMismatchFallback: "สกุลเงินของ benchmark ไม่ตรงกับสกุลเงินของพอร์ต",
        currencyMismatch: (symbol: string, currency: string) =>
          `${symbol} ไม่ได้ quote เป็น ${currency}`,
        missingBenchmarkFallback: "ตั้งค่า benchmark เพื่อเปิดการเปรียบเทียบ",
        missingBenchmarkHistory: (symbol: string) => `ไม่มีประวัติราคาแคชสำหรับ ${symbol}`,
        missingAbsoluteReturn:
          "กราฟ absolute return ต้องมี net invested เป็นบวกและประวัติ benchmark ที่เปรียบเทียบได้",
        default: "กราฟ benchmark ยังไม่พร้อมใช้งาน",
      },
    },
    portfolio: {
      eyebrow: "มูลค่าพอร์ต",
      title: "ประวัติมูลค่าพอร์ต",
      timeframe: "ช่วงเวลาของกราฟมูลค่าพอร์ต",
      rangeSummary: "สรุปช่วงมูลค่าพอร์ต",
      unavailable: {
        noTransactions: "เพิ่มรายการซื้อขายเพื่อเริ่มกราฟพอร์ต",
        mixedCurrency: "หยุดกราฟพอร์ตไว้เมื่อประวัติรายการซื้อขายมีหลายสกุลเงิน",
        missingPortfolioHistory: "ประวัติราคาไม่ครบสำหรับ performance ของทั้งพอร์ต",
        default: "ยังไม่มีข้อมูลกราฟพอร์ต",
      },
    },
  },
  holdings: {
    pageEyebrow: "หุ้นที่ถือ",
    pageTitle: "สถานะลงทุน",
    statusLabel: "สถานะหุ้นที่ถือ",
    open: "เปิด",
    priced: "มีราคา",
    missing: "ขาดราคา",
    latestCache: "แคชล่าสุด",
    table: {
      eyebrow: "หุ้นที่ถือ",
      title: "สถานะปัจจุบัน",
      toolsLabel: "เครื่องมือตารางหุ้นที่ถือ",
      filtersLabel: "ตัวกรองหุ้นที่ถือ",
      performanceBasisLabel: "ฐานเทียบ Performance",
      performanceBasis: {
        price: "ราคาย้อนหลัง",
        cost: "ต้นทุนจริง",
      },
      performanceTimeframesLabel: "ช่วงเวลา Performance",
      refreshPrices: "รีเฟรชราคา",
      refreshing: "กำลังรีเฟรช...",
      refreshStarted: "เริ่มรีเฟรชราคาแล้ว",
      noOpenPositions: "ยังไม่มีสถานะลงทุนที่เปิดอยู่ เพิ่มรายการซื้อ แล้วหุ้นที่ถือจะแสดงที่นี่",
      searchPlaceholder: "Symbol, ชื่อ, ตลาด",
      positionsUnit: "สถานะ",
      noMatches: "ไม่มีสถานะที่ตรงกับตัวกรองปัจจุบัน",
      shownTotal: "รวมที่แสดง",
      noPriceYet: "ยังไม่มีราคา",
      noData: "ไม่มีข้อมูล",
      asOf: (date: string) => `ณ ${date}`,
      updatedWithIssues: (count: number) =>
        `อัปเดตราคาแล้ว แต่ยังมี ${count} symbols ที่ต้องตรวจสอบ`,
      updatedPrices: (count: number) => `อัปเดต ${count} ราคาแล้ว`,
      refreshFailed: "รีเฟรชข้อมูลตลาดไม่สำเร็จ",
      filter: {
        all: "ทั้งหมด",
        gain: "กำไร",
        loss: "ขาดทุน",
        missing: "ขาดราคา",
      },
      timeframes: {
        "1D": "1D",
        "1W": "1W",
        "1M": "1M",
        YTD: "YTD",
        "1Y": "1Y",
        "3Y": "3Y",
        "5Y": "5Y",
        MAX: "MAX",
      },
      columns: {
        symbol: "Symbol",
        quantity: "จำนวน",
        averageCost: "ต้นทุนเฉลี่ย",
        totalCost: "ต้นทุนรวม",
        lastPrice: "ราคาล่าสุด",
        oneDayGain: "1D",
        performance: (timeframe: string) => `Performance ${timeframe}`,
        marketValue: "มูลค่าตลาด",
        unrealizedPnl: "Unrealized P&L",
        weight: "น้ำหนัก",
      },
      lots: {
        expandColumn: "รายละเอียดรายการซื้อ",
        expand: (symbol: string) => `แสดงรายการซื้อของ ${symbol}`,
        collapse: (symbol: string) => `ซ่อนรายการซื้อของ ${symbol}`,
        noOpenLots: "ไม่มีรายการซื้อที่ยังเปิดอยู่",
        openLot: "Lot ที่ยังถืออยู่",
        fee: (value: string) => `ค่าธรรมเนียม ${value}`,
        originalQuantity: (quantity: string) => `ซื้อเดิม ${quantity}`,
        costLabel: "ต้นทุน",
        columns: {
          date: "วันที่ซื้อ",
          price: "ราคาซื้อ",
          quantity: "จำนวนที่เหลือ",
          gain: "กำไรรวม",
          value: "มูลค่า",
          note: "โน้ต",
        },
      },
      detail: {
        title: "รายละเอียดหุ้น",
        open: (symbol: string) => `ดูรายละเอียด ${symbol}`,
        loading: "กำลังโหลดรายละเอียด...",
        error: "โหลดรายละเอียดหุ้นไม่สำเร็จ",
        viewFullPage: "ดูหน้าเต็ม",
      },
    },
    summary: {
      openPositions: "สถานะที่เปิดอยู่",
      openCostBasis: "ต้นทุนสถานะเปิด",
      marketValue: "มูลค่าตลาด",
      unrealizedPnl: "Unrealized P&L",
      realizedPnl: "Realized P&L",
      noOpenHoldings: "ยังไม่มีหุ้นที่ถืออยู่",
      openLedger: (count: number) => `${count} สถานะยังเปิดอยู่จากสมุดรายการซื้อขาย`,
      calculatedOpenOnly: "คำนวณจากสถานะที่เปิดอยู่เท่านั้น",
      usingCachedPrices: "ใช้ราคาแคช",
      usingCachedPricesAsOf: (date: string) => `ใช้ราคาแคช ณ ${date}`,
      openGainLoss: "กำไรหรือขาดทุนของสถานะเปิดเทียบกับต้นทุน",
      closedTradeResult: "ผลลัพธ์เทรดปิดถึงตอนนี้",
      waiting: "รอข้อมูล",
      waitingForPrice: "รอราคา",
      mixedCurrency: "หลายสกุลเงิน",
      currencyBreakdown: (currency: string, value: string) => `${currency}: ${value}`,
      priceCoverageNoOpen: "ยังไม่มีสถานะที่เปิดอยู่",
      priceCoverageFull: (count: number) => `ราคาแคชครอบคลุมครบทั้ง ${count} สถานะ`,
      priceCoverageFullAsOf: (count: number, date: string) =>
        `ราคาแคชครอบคลุมครบทั้ง ${count} สถานะ ณ ${date}`,
      priceCoveragePartial: (priced: number, open: number, waiting: string) =>
        `${priced} จาก ${open} สถานะมีราคา; รอ ${waiting}`,
      moreSymbols: (count: number) => ` +${count} เพิ่มเติม`,
    },
    allocation: {
      ariaLabel: "กราฟสัดส่วนหุ้นที่ถือ",
      other: "อื่น ๆ",
      positions: (count: number) => `${count} สถานะ`,
      ofHoldings: "ของหุ้นที่ถือ",
    },
  },
  transactions: {
    pageEyebrow: "Ledger",
    pageTitle: "รายการซื้อขาย",
    pageDescription: "บันทึกซื้อ ขาย และค่าธรรมเนียมโดยไม่ต้องเลือก instrument ไว้ก่อน",
    aggregateReadOnly:
      "พอร์ตรวมเป็นโหมดอ่านอย่างเดียว เลือกพอร์ตจริงก่อนเพิ่ม แก้ไข ลบ นำเข้า ส่งออก หรือรีเฟรชข้อมูลตลาด",
    summaryLabel: "สรุปรายการซื้อขาย",
    recorded: "บันทึกแล้ว",
    traded: "ซื้อขาย",
    open: "เปิด",
    latest: "ล่าสุด",
    selectable: "เลือกได้",
    allInstruments: "เครื่องมือทั้งหมด",
    syncing: "กำลังอัปเดตรายการ...",
    excel: {
      eyebrow: "Excel",
      title: "นำเข้า/ส่งออกรายการ",
      downloadTemplate: "ดาวน์โหลดเทมเพลต",
      exportLedger: "ส่งออก ledger",
      downloadingTemplate: "กำลังดาวน์โหลดเทมเพลต...",
      exportingLedger: "กำลังส่งออก ledger...",
      file: "ไฟล์ Excel",
      selectedFile: "ไฟล์ที่เลือก",
      chooseFile: "เลือกไฟล์",
      noFileSelected: "ยังไม่ได้เลือกไฟล์",
      preview: "พรีวิว",
      previewing: "กำลังพรีวิว...",
      importReady: "นำเข้าแถวที่พร้อม",
      importing: "กำลังนำเข้า...",
      previewSummary: "สรุปการนำเข้า Excel",
      total: "ทั้งหมด",
      ready: "พร้อม",
      skipped: "ข้าม",
      error: "ผิดพลาด",
      row: (rowNumber: number) => `แถว ${rowNumber}`,
      chooseFileFirst: "เลือกไฟล์ .xlsx ก่อน",
      importFailed: "นำเข้าไฟล์ Excel ไม่สำเร็จ",
      imported: (count: number) => `นำเข้า ${count} รายการแล้ว`,
    },
    form: {
      editEyebrow: "แก้ไขรายการซื้อขาย",
      newEyebrow: "รายการซื้อขายใหม่",
      updateTitle: "อัปเดตรายการ",
      recordTitle: "บันทึกรายการ",
      instrument: "Instrument",
      instrumentHint: "ค้นหา instrument ที่บันทึกไว้ หรือเพิ่มใหม่",
      close: "ปิด",
      clearInstrumentSearch: "ล้างการค้นหา instrument",
      addInstrument: "เพิ่ม instrument",
      addingInstrument: "กำลังเพิ่ม instrument...",
      searchInstrument: "ค้นหา instrument",
      searchInstrumentPlaceholder: "พิมพ์ ASTS03, AAPL หรือชื่อบริษัท",
      searching: "กำลังค้นหา...",
      noMatchingInstruments: "ไม่พบ instrument ที่ตรงกัน",
      noInstruments: "ยังไม่มี instrument เพิ่ม instrument ก่อนบันทึกรายการซื้อขาย",
      chooseInstrument: "เลือก instrument",
      currentQuantity: (quantity: string) => `จำนวนปัจจุบัน: ${quantity} หน่วย`,
      selectBeforeSaving: "เลือก instrument ที่ตรงกันก่อนบันทึก",
      tradeDate: "วันที่ซื้อขาย",
      side: "ฝั่ง",
      broker: "Broker",
      buy: "Buy",
      sell: "Sell",
      quantity: "จำนวน",
      price: "ราคา",
      fee: "ค่าธรรมเนียม",
      notes: "โน้ต",
      notesPlaceholder: "โน้ตเพิ่มเติม เช่น fill context หรือเหตุผลการซื้อขาย",
      cancelEdit: "ยกเลิกการแก้ไข",
      updating: "กำลังอัปเดต...",
      saving: "กำลังบันทึก...",
      refreshing: "กำลังรีเฟรช...",
      updateTransaction: "อัปเดตรายการ",
      saveTransaction: "บันทึกรายการ",
      couldNotSave: "บันทึกรายการไม่สำเร็จ",
      couldNotUpdate: "อัปเดตรายการไม่สำเร็จ",
      transactionUpdated: "อัปเดตรายการแล้ว",
      transactionSaved: "บันทึกรายการแล้ว",
      instrumentSearchUnavailable: "ค้นหา instrument ไม่พร้อมใช้งานตอนนี้",
      instrumentCouldNotSave: "บันทึก instrument ไม่สำเร็จ",
      instrumentAlreadyAdded: (symbol: string) =>
        `${symbol} ถูกเพิ่มไว้แล้ว เลือกจากช่อง Instrument ด้านล่างแทน`,
      addedAndSelected: (symbol: string) => `เพิ่มและเลือก ${symbol} แล้ว`,
      selected: (symbol: string) => `เลือก ${symbol} แล้ว`,
      insufficientQuantity: (quantity: string) =>
        `จำนวนขายมากกว่าที่ถืออยู่ จำนวนสูงสุดที่ขายได้คือ ${quantity}`,
      saved: "บันทึกแล้ว",
      add: "เพิ่ม",
    },
    table: {
      eyebrow: "Ledger",
      title: "รายการล่าสุด",
      toolsLabel: "เครื่องมือตารางรายการซื้อขาย",
      noTransactions: "ยังไม่มีรายการซื้อขาย รายการแรกจะแสดงที่นี่ทันที",
      searchPlaceholder: "Symbol, วันที่, โน้ต",
      transactionsUnit: "รายการ",
      noMatches: "ไม่พบเทรดที่ตรงกับการค้นหาปัจจุบัน",
      deleteCouldNot: "ลบรายการไม่สำเร็จ",
      deleteConfirm: (side: string, quantity: string, symbol: string, date: string) =>
        `ลบ ${side} ${quantity} ${symbol} จากวันที่ ${date}?`,
      refreshing: "กำลังอัปเดตรายการ...",
      deleting: "กำลังลบ...",
      delete: "ลบ",
      edit: "แก้ไข",
      columns: {
        date: "วันที่",
        instrument: "Instrument",
        side: "ฝั่ง",
        broker: "Broker",
        portfolio: "พอร์ต",
        quantity: "จำนวน",
        price: "ราคา",
        fee: "ค่าธรรมเนียม",
        net: "สุทธิ",
        notes: "โน้ต",
        actions: "จัดการ",
      },
    },
  },
} as const;
